### ISSUE TITLE
VSCode command 'Format Document' throws error, doesn't format

### ISSUE THREAD

**Issue by tillydray** [monofon/hindent-format#8]
When I run the command `Format Document` in VSCode, the below error is thrown in `Log (Window)`. However, if I run `./hindent <file>` then it works and respects my `hindent.yaml`.

```[2018-05-21 08:22:34.255] [renderer5] [error] Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
	at HindentFormatEditsProvider.formatHindent (/Users/jason.fry/.vscode/extensions/monofon.hindent-format-0.0.8/out/extension.js:42:33)
	at HindentFormatEditsProvider.provideDocumentFormattingEdits (/Users/jason.fry/.vscode/extensions/monofon.hindent-format-0.0.8/out/extension.js:50:30)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:823
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:621
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:76:378)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:584)
	at e.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:777)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:667:231
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:662:852)
	at e.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:667:193)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:599:737)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:599:455)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:598:529)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:598:298)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:597:226
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:600:324
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:88:119
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:89:496)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

**Comment by monofon** [comment]
I will look in to that, when I get to it. Maybe next week.

**Comment by irvinlim** [comment]
@JasonMFry, the reason is because VS Code can't seem to locate the `hindent` binary. Explicitly specifying the `hindent-format.command` setting would fix it.

**Comment by tillydray** [comment]
At this point we no longer use hindent or I would try to reproduce the error again, but I'm pretty sure I had `hindent-format.command` set correctly, but maybe not.
